server {
	listen 80;
	server_name dolovcak.duckdns.org;

	root /var/www/failover;

	location / {
		proxy_pass http://landing_backend;

	        include /etc/nginx/http.d/proxy-common.inc;
	}

	error_page 500 502 503 504 /failover.html;

	location = /failover.html {
		internal;
		try_files /failover.html =500;
	}
}
