server {
	listen 80;
	server_name dolovcak.duckdns.org;
	return 301 https://$host$request_uri;
}

server {
	listen 443 ssl;
	http2 on;
	server_name dolovcak.duckdns.org;

	root /var/www;

	ssl_certificate /etc/nginx/certs/dolovcak.duckdns.org/fullchain.pem;
	ssl_certificate_key /etc/nginx/certs/dolovcak.duckdns.org/key.pem;
	ssl_protocols TLSv1.2 TLSv1.3;

	# proxy bypass for acme challenge:
	location ^~ /.well-known/acme-challenge/ {
        	root /var/www/acme;
	}

	location / {
		proxy_pass http://landing_backend;

	        include /etc/nginx/http.d/proxy-common.inc;
	}

	error_page 500 502 503 504 /failover;

	location = /failover {
		internal;
		try_files /failover/failover.html =500;
	}
}
