# force HTTPS:
server {
	listen 80;
	server_name dolovcak.duckdns.org;
	return 301 https://$host$request_uri;
}

server {
	listen 443 ssl;
	http2 on;
	server_name dolovcak.duckdns.org;
	include /etc/nginx/http.d/snippets/ssl-common.inc;

	root /var/www;

	# proxy bypass for acme challenge:
	location ^~ /.well-known/acme-challenge/ {
        	root /var/www/acme;
	}
	
	include /etc/nginx/http.d/routes/*.conf;

	location / {
		proxy_pass http://www_backend/;
		include /etc/nginx/http.d/snippets/proxy-common.inc;
	}

	error_page 500 502 503 504 /failover;

	location = /failover {
		internal;
		try_files /failover/failover.html =500;
	}
}
