location = /app/slskd { return 301 /app/slskd/; }
location /app/slskd/ {
    proxy_pass http://slskd_backend;
    proxy_set_header Host $host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_request_buffering off;
}
