[Interface]
Address = 10.10.0.1/24
ListenPort = 51820
PostUp = wg set %i private-key /etc/wireguard/server.key
PostDown = true

[Peer]
PublicKey = muPO0kyBA8L+HAW2qs7Ttjzz5Haoxq88SzSya3CQt3k=
AllowedIPs = 10.10.0.2/32
